site_name: Kotlin For Everything
repo_name: Kotlin For Everything

repo_url: https://github.com/Foso/KotlinForEverything
site_url: https://github.com/Foso/KotlinForEverything
docs_dir: 'docs'
edit_uri: 'tree/master/docs/'
theme:
  name: 'material'
  language: en
  custom_dir: 'docs/theme'
  font:
    text: Ubuntu
    code: Jetbrains Mono
  palette:
    primary: 'deep-blue'
    accent: 'deep-purple'
  feature:
    - tabs: true
    - instant
  icon:
    logo: material/cloud
extra:
  manifest: manifest.webmanifest
  social:
    - icon: fontawesome/brands/github-alt
      link: 'https://github.com/foso'
    - icon: fontawesome/brands/twitter
      link: 'https://twitter.com/jklingenberg_'
    - icon: fontawesome/solid/external-link-alt
      link: 'http://www.jensklingenberg.de'
nav:
  - 'Kotlin For Everything':
      - 'Overview': index.md
      - 'Multiplatform' :
           - 'Gradle Plugin' : multiplatform/gradleplugin.md
           - 'KMM Plugin' : multiplatform/kmmplugin.md
      - 'KotlinJs':
           - 'Overview': kotlinjs/overview.md
           - 'js() Function': kotlinjs/jsfunction.md
           - 'Dynamic': kotlinjs/dynamic.md
           - 'Interop':
               - 'Call Kotlin from kotlinjs': kotlinjs/interop/callkotlinfromjavascript.md
               - 'Call JavaScript from Kotlin': kotlinjs/interop/calljavascriptfromkotlin.md
           - 'Debugging': kotlinjs/debugging.md
           - 'Dependencies': kotlinjs/dependencies.md
      - 'iOS':
          - 'Overview': ios/overview.md
          - 'Getting started': ios/getstarted.md
          - 'Framework': ios/framework.md
          - 'Debugging': ios/debugging.md
markdown_extensions:
  - smarty
  - codehilite:
      guess_lang: false
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.emoji
  - tables
  - admonition

plugins:
  - search
  - minify:
      minify_html: true